name: Generate Translations

on:
  push:
    branches:
      - master

jobs:
  generate-translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: WordPress POT/PO/MO Generator
        uses: nikitasinelnikov/action-wp-pot-po-mo-generator@main
        with:
          destination_path: './languages'
          slug: 'messaging'
          text_domain: 'um-messaging'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
